[package]
name = "clippy-output"
version = "0.1.0"
authors = ["Makoto <makoto@emurasoft.com>"]
edition = "2018"
documentation = "https://docs.rs/clippy-output/"

[dependencies]
anyhow = "1.0"
terminal_size = "0.1"
